name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      HISTORY_FILE: test_history.csv  # 👈 Required for repl-related tests

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=app tests/